id: I100E7DAD
initial_creation_type: ebook
source_metadata:
  id: RDI-KK-04
  title: དམ་ཆོས་ཡིད་བཞིན་ནོར་བུ་ཐར་པ་རིན་པོ་ཆེའི་རྒྱན།
  author: མཛད་པ་པོ། ཆོས་རྒྱལ་དྭགས་པོ་ལྷ་རྗེ།
  authors: &id001
  - མཛད་པ་པོ། ཆོས་རྒྱལ་དྭགས་པོ་ལྷ་རྗེ།
  sku: RDI-KK-04
  cover: Cover.jpeg
  volume: {}
  title_source: epub:dc:title:ambiguous-layer
ebook_metadata:
  title: དམ་ཆོས་ཡིད་བཞིན་ནོར་བུ་ཐར་པ་རིན་པོ་ཆེའི་རྒྱན།
  authors: *id001
  sku: RDI-KK-04
  cover: Cover.jpeg
layers:
- Author
- BookNumber
- BookTitle
- Chapter
- Citation
- Commentary
- Sabche
- Tsawa
- Yigchung
